export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';

export const LOGIN_REQUEST = 'LOGIN-REQUEST';
export const LOGIN_SUCCESS = 'LOGIN-SUCCESS';
export const LOGIN_FAILURE = 'LOGIN-FAILURE';

export const REGISTER_REQUEST = 'REGISTER-REQUEST';
export const REGISTER_FAILURE = 'REGISTER-FAILURE';
export const REGISTER_CREATED_SUCCESS = 'REGISTER-CREATED-SUCCESS';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER-UPDATED-SUCCESS';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
